# Generated by Django 5.1.2 on 2024-11-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userseat_user_userseat_booking'),
        ('app', '0002_user_is_active_user_last_activity'),
    ]

    operations = [
    ]
