# Generated by Django 5.1.3 on 2025-03-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact_seat_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='card', max_length=50),
        ),
    ]
