# Generated by Django 5.1.2 on 2025-03-14 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
