# Generated by Django 5.1.2 on 2025-03-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_qr_code_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
