# Generated by Django 5.1.2 on 2025-03-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
